# Generated by Django 6.1.1 on 2026-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveIntegerField(verbose_name='S.No')),
                ('tl_no', models.CharField(max_length=100, verbose_name='TL No')),
                ('received_date', models.DateField(verbose_name='Received Date')),
                ('sender_name', models.CharField(max_length=200, verbose_name='Sender Name')),
                ('letter_date', models.DateField(verbose_name='Letter Date')),
                ('section_name', models.CharField(max_length=200, verbose_name='Section Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('current_status', models.CharField(choices=[('Pending', 'Pending'), ('Disposed', 'Disposed')], default='Pending', max_length=20, verbose_name='Current Status')),
                ('tl_pdf', models.FileField(blank=True, null=True, upload_to='tl_pdfs/', verbose_name='TL PDF')),
                ('answer_pdf', models.FileField(blank=True, null=True, upload_to='answer_pdfs/', verbose_name='Answer PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
