# Generated by Django 6.1.1 on 2026-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeLimit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelimit',
            name='current_situation',
            field=models.TextField(blank=True, verbose_name='वर्तमान स्थिति'),
        ),
    ]
