# Generated by Django 6.1.1 on 2026-09-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeLimit', '0002_timelimit_current_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelimit',
            name='subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subject'),
        ),
    ]
