# Generated by Django 6.1.1 on 2026-09-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeLimit', '0003_timelimit_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelimit',
            name='current_situation',
        ),
        migrations.RemoveField(
            model_name='timelimit',
            name='letter_date',
        ),
        migrations.AddField(
            model_name='timelimit',
            name='letter_no_date',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='क्र/दिनांक'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='current_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disposed', 'Disposed')], default='Pending', max_length=20, verbose_name='वर्तमान स्थिति'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='description',
            field=models.TextField(blank=True, verbose_name='विवरण'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='received_date',
            field=models.DateField(verbose_name='प्राप्ति दिनांक'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='section_name',
            field=models.CharField(max_length=200, verbose_name='संबंधित शाखा का नाम'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='sender_name',
            field=models.CharField(max_length=200, verbose_name='प्रेषक'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='sno',
            field=models.PositiveIntegerField(verbose_name='स.क्र.'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='विषय'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='tl_no',
            field=models.CharField(max_length=100, verbose_name='TL No.'),
        ),
    ]
