# Generated by Django 6.1.1 on 2026-09-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeLimit', '0004_remove_timelimit_current_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelimit',
            name='current_situation',
            field=models.TextField(blank=True, default='', verbose_name='वर्तमान स्थिति'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='current_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disposed', 'Disposed')], default='Pending', max_length=20, verbose_name='स्थिति'),
        ),
    ]
