# Generated by Django 6.1.1 on 2026-09-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeLimit', '0005_timelimit_current_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelimit',
            name='answer_pdf_drive_url',
            field=models.URLField(blank=True, default='', verbose_name='Answer PDF Drive URL'),
        ),
        migrations.AddField(
            model_name='timelimit',
            name='tl_pdf_drive_url',
            field=models.URLField(blank=True, default='', verbose_name='TL PDF Drive URL'),
        ),
    ]
